# WIP
# This workflow builds images on the action runner then pushes them to GHCR
name: Build & push images to GHCR

on:
  push:
    branches: [ghcr]
    #tags: ["v*"]
  workflow_dispatch: # Allow manual triggering

env:
  APP_REPO_NAME: ${{ vars.APP_REPO_NAME || 'jchook/madi' }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for version script to work properly

      - name: Read version stamp
        id: version
        run: echo "APP_VERSION=$(./server/bin/version)" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./compose/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.APP_REPO_NAME }}-api:${{ env.APP_VERSION }}
            ghcr.io/${{ env.APP_REPO_NAME }}-api:latest
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            TARGET=server
            COMMAND=api
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./compose/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.APP_REPO_NAME }}-worker:${{ env.APP_VERSION }}
            ghcr.io/${{ env.APP_REPO_NAME }}-worker:latest
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            TARGET=server
            COMMAND=worker
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Client image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./compose/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.APP_REPO_NAME }}-client:${{ env.APP_VERSION }}
            ghcr.io/${{ env.APP_REPO_NAME }}-client:latest
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            TARGET=client
            COMMAND=builder
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./compose/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.APP_REPO_NAME }}-nginx:${{ env.APP_VERSION }}
            ghcr.io/${{ env.APP_REPO_NAME }}-nginx:latest
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
            TARGET=client
            COMMAND=runtime
          cache-from: type=gha
          cache-to: type=gha,mode=max
